// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.libereco.core.domain;

import com.libereco.core.domain.EbayListing;
import java.io.Serializable;

privileged aspect EbayListing_Roo_Serializable {
    
    declare parents: EbayListing implements Serializable;
    
    private static final long EbayListing.serialVersionUID = 1L;
    
}
