// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.libereco.core.domain;

public class EtsyListingBuilder extends EtsyListingBuilderBase<EtsyListingBuilder> {
    public static EtsyListingBuilder etsyListing() {
        return new EtsyListingBuilder();
    }

    public EtsyListingBuilder() {
        super(new EtsyListing());
    }

    public EtsyListing build() {
        return getInstance();
    }
}

class EtsyListingBuilderBase<GeneratorT extends EtsyListingBuilderBase<GeneratorT>> {
    private EtsyListing instance;

    protected EtsyListingBuilderBase(EtsyListing aInstance) {
        instance = aInstance;
    }

    protected EtsyListing getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withId(Long aValue) {
        instance.setId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withVersion(Integer aValue) {
        instance.setVersion(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLiberecoListing(LiberecoListing aValue) {
        instance.setLiberecoListing(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withListingId(int aValue) {
        instance.setListingId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withWhoMade(EtsyWhoMade aValue) {
        instance.setWhoMade(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSupply(boolean aValue) {
        instance.setSupply(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withWhenMade(EtsyWhenMade aValue) {
        instance.setWhenMade(aValue);

        return (GeneratorT) this;
    }
}
