package com.libereco.core.domain;

public enum LiberecoCategory {

    CAT_BOOKS, CAT_MOVIES_MUSIC_GAME, CAT_COMPUTER_OFFICE, CAT_ELECTRONICS, CAT_HOME_GARDEN_PETS, CAT_GROCERY_HEALTH_BEAUTY, CAT_TOYS_KIDS_BABY, CAT_CLOTHING_SHOES_JEWELLERY, CAT_SPORTS_OUTDOOR;
}
