// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.libereco.core.domain;

import com.libereco.core.domain.LiberecoListing;
import java.io.Serializable;

privileged aspect LiberecoListing_Roo_Serializable {
    
    declare parents: LiberecoListing implements Serializable;
    
    private static final long LiberecoListing.serialVersionUID = 1L;
    
}
