package com.libereco.core.domain;

public enum ShippingType {

    FLAT, CALCULATED, CALCULATED_DOMESTIC_FLAT_INTERNATIONAL, CUSTOM_CODE, FLAT_DOMESTIC_CALCULATED_INTERNATIONAL, FREE, FREIGHT, FREIGHT_FLAT, NOT_SPECIFIED;
}
