// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.libereco.core.domain;

import com.libereco.core.domain.EbayListingIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EbayListingIntegrationTest_Roo_Configurable {
    
    declare @type: EbayListingIntegrationTest: @Configurable;
    
}
