// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.libereco.springsocial.etsy.api;

import java.util.Date;

public class EtsyUserBuilder extends EtsyUserBuilderBase<EtsyUserBuilder> {
    public static EtsyUserBuilder etsyUser() {
        return new EtsyUserBuilder();
    }

    public EtsyUserBuilder() {
        super(new EtsyUser());
    }

    public EtsyUser build() {
        return getInstance();
    }
}

class EtsyUserBuilderBase<GeneratorT extends EtsyUserBuilderBase<GeneratorT>> {
    private EtsyUser instance;

    protected EtsyUserBuilderBase(EtsyUser aInstance) {
        instance = aInstance;
    }

    protected EtsyUser getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withUserId(String aValue) {
        instance.setUserId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withLoginName(String aValue) {
        instance.setLoginName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPrimaryEmail(String aValue) {
        instance.setPrimaryEmail(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCreationDate(Date aValue) {
        instance.setCreationDate(aValue);

        return (GeneratorT) this;
    }
}
