// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.libereco.springsocial.etsy.api;

public class ListingBuilder extends ListingBuilderBase<ListingBuilder> {
    public static ListingBuilder listing() {
        return new ListingBuilder();
    }

    public ListingBuilder() {
        super(new Listing());
    }

    public Listing build() {
        return getInstance();
    }
}

class ListingBuilderBase<GeneratorT extends ListingBuilderBase<GeneratorT>> {
    private Listing instance;

    protected ListingBuilderBase(Listing aInstance) {
        instance = aInstance;
    }

    protected Listing getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withQuantity(int aValue) {
        instance.setQuantity(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withTitle(String aValue) {
        instance.setTitle(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withDescription(String aValue) {
        instance.setDescription(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPrice(double aValue) {
        instance.setPrice(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withShippingTemplateId(int aValue) {
        instance.setShippingTemplateId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withCategoryId(int aValue) {
        instance.setCategoryId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withWhoMade(String aValue) {
        instance.setWhoMade(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSupply(boolean aValue) {
        instance.setSupply(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withWhenMade(String aValue) {
        instance.setWhenMade(aValue);

        return (GeneratorT) this;
    }
}
