// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.libereco.springsocial.etsy.api;

public class ShippingTemplateInfoBuilder extends ShippingTemplateInfoBuilderBase<ShippingTemplateInfoBuilder> {
    public static ShippingTemplateInfoBuilder shippingTemplateInfo() {
        return new ShippingTemplateInfoBuilder();
    }

    public ShippingTemplateInfoBuilder() {
        super(new ShippingTemplateInfo());
    }

    public ShippingTemplateInfo build() {
        return getInstance();
    }
}

class ShippingTemplateInfoBuilderBase<GeneratorT extends ShippingTemplateInfoBuilderBase<GeneratorT>> {
    private ShippingTemplateInfo instance;

    protected ShippingTemplateInfoBuilderBase(ShippingTemplateInfo aInstance) {
        instance = aInstance;
    }

    protected ShippingTemplateInfo getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withTitle(String aValue) {
        instance.setTitle(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withOriginCountryId(int aValue) {
        instance.setOriginCountryId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withDestinationCountryId(int aValue) {
        instance.setDestinationCountryId(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPrimaryCost(float aValue) {
        instance.setPrimaryCost(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withSecondaryCost(float aValue) {
        instance.setSecondaryCost(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withShippingTemplateId(int aValue) {
        instance.setShippingTemplateId(aValue);

        return (GeneratorT) this;
    }
}
